"""Add conversation history table

Revision ID: 0daa8062ab81
Revises: a5ff26f47f35
Create Date: 2026-02-06 10:45:01.998095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0daa8062ab81'
down_revision: Union[str, None] = 'a5ff26f47f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_history_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_history_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_history_id'))

    op.drop_table('conversation_history')
    # ### end Alembic commands ### 